# SPDX-FileCopyrightText: 2026 Jan Matyas <info@janmatyas.net>
# SPDX-License-Identifier: MIT

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "PyOpenocdClient"
version = "0.3.0-dev"
authors = [
  { name="Jan Matyas", email="info@janmatyas.net" },
]
description = "Library for controlling OpenOCD from Python programs"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/HonzaMat/PyOpenocdClient"
Issues = "https://github.com/HonzaMat/PyOpenocdClient/issues"
Documentation = "https://pyopenocdclient.readthedocs.io/en/latest/"

[project.scripts]
openocd_cmd = "py_openocd_client.cli:main"

[tool.setuptools.package-data]
py_openocd_client = ["py.typed"]
