name: Code quality checks
on:
  push:
  schedule:
    - cron: "09 9 * * *"
    #- cron: "35 20 * * 1"
jobs:
  code_quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Install code quality tools
        run: |
          python3 -m pip install --user -r requirements_code_quality.txt

      - name: Perform the check
        run: |
          python3 run_code_quality_check.py


