name: Integration tests
on: [push]
jobs:
  integration_tests:
    name: Integration test against OpenOCD
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        openocd_version:
          - vanilla-v0.10.0
          - vanilla-v0.11.0
          - vanilla-v0.12.0
          - vanilla-master
          - riscv-master
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Build OpenOCD ${{ matrix.openocd_version }}
        run: |
          mkdir -p oocd-build && cd oocd-build
          python3 ../tests_integration/py_openocd_client/build_openocd.py ${{ matrix.openocd_version }}

      - name: Run integration test
        run: |
          python3 -m pytest tests_integration/py_openocd_client/ -vv --openocd-path oocd-build/install/${{ matrix.openocd_version }}/bin/openocd

