name: Integration tests
on: [push]
jobs:
  integration_tests_linux:
    name: OpenOCD on Linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        openocd_version:
          - vanilla-v0.10.0
          - vanilla-v0.11.0
          - vanilla-v0.12.0
          - vanilla-master
          - riscv-master
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Build OpenOCD ${{ matrix.openocd_version }}
        run: |
          mkdir -p oocd-build && cd oocd-build
          python3 ../tests_integration/build_openocd.py ${{ matrix.openocd_version }}

      - name: Install pytest
        run: |
          python3 -m pip install --user pytest

      - name: Run integration test
        run: |
          python3 run_tests.py integration --force-pythonpath --openocd-path oocd-build/install/${{ matrix.openocd_version }}/bin/openocd

  integration_test_windows:
    name: OpenOCD on Windows
    runs-on: windows-2022
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Download OpenOCD
        run: |
          Invoke-WebRequest -Uri "https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-win32-x64.zip" -OutFile "openocd.zip"

      - name: Unzip OpenOCD
        run: |
          unzip openocd.zip

      - name: Install pytest
        run: |
          python3 -m pip install pytest

      - name: Run integration testing
        run: |
          python3 run_tests.py integration --force-pythonpath --openocd-path xpack-openocd-0.12.0-3\\bin\\openocd


